README.md

Saves groping around Google for abit.
Thanks for providing a turn-key solution!

+ AppSync link

---

packages/aws-appsync/src/link/signer/signer.js

Fixing `ReferenceError: scope is not defined`
Fixes #111

fix scope is not defined error

---

packages/aws-appsync/src/link/subscription-handshake-link.js

Disconnect client if no more topics are subscribed

---

README.md

Just making things prettier :-D

add syntax highlighting to readme

---

packages/aws-appsync-react/package.json
packages/aws-appsync/package.json
packages/aws-appsync/src/cache/index.js
packages/aws-appsync/src/cache/offline-cache.js
packages/aws-appsync/src/client.js
packages/aws-appsync/src/link/index.js
packages/aws-appsync/src/link/offline-link.js
packages/aws-appsync/src/link/subscription-handshake-link.js
packages/aws-appsync/src/store.js

Fixes: #65 
Fixes: #72 
Fixes: #84 
Fixes: #133
- Implement bookkeeping for offline mutations
- Store cache snapshot before processing offline queue

fix(cache):Implement bookkeeping for offline mutations

---

packages/aws-appsync/src/link/auth-link.js
packages/aws-appsync/src/link/signer/signer.js

fix(auth):Invalid AUTH_TYPE

---

packages/aws-appsync/package.json
packages/aws-appsync/src/link/subscription-handshake-link.js
packages/aws-appsync/src/vendor/paho-mqtt.js
yarn.lock

Fixes: #10 
Fixes: #77 
Fixes: #82 
Fixes: #104 
Add copy of paho-client to vendor folder with patch from eclipse/paho.mqtt.javascript#153

fix(subscriptions):Improve SSR support

---

packages/aws-appsync/src/cache/offline-cache.js
packages/aws-appsync/src/client.js
packages/aws-appsync/src/link/index.js
packages/aws-appsync/src/link/offline-link.js

fix(offline):Improve cache snapshotting

---

packages/aws-appsync/src/client.ts

Fixes #159
Always pass refetchQueries when offline is disabled.

fix(client): Always pass refetchQueries when offline is disabled.

---

packages/aws-appsync/src/link/auth-link.ts

fix for #128
replacing utf-8 with UTF-8 at auth-link.ts

fix(auth): replacing utf-8 with UTF-8

---

packages/aws-appsync/src/link/auth-link.ts
packages/aws-appsync/src/link/index.ts
packages/aws-appsync/src/link/signer/index.ts
packages/aws-appsync/src/link/signer/signer.ts

Fixes #153
Export SigV4 Signer

feat(signer): Export SigV4 Signer

---

packages/aws-appsync/src/link/offline-link.ts

Fixes #170
Fixes #158
Enqueue mutation even if no optimisticResponse is provided

fix(offline): Enqueue mutation even if no optimisticResponse is provided

---

packages/aws-appsync-react/package.json
packages/aws-appsync-react/src/index.ts
packages/aws-appsync-react/src/offline-helpers.tsx
packages/aws-appsync-react/src/rehydrated-rn.tsx
packages/aws-appsync-react/src/rehydrated.tsx
packages/aws-appsync-react/tsconfig.json
packages/aws-appsync/package.json
packages/aws-appsync/src/cache/offline-cache.ts
packages/aws-appsync/src/client.ts
packages/aws-appsync/src/helpers/offline.ts
packages/aws-appsync/src/index.ts
packages/aws-appsync/src/link/offline-link.ts
yarn.lock

feat(offline): Offline helpers

---

packages/aws-appsync-react/package.json
packages/aws-appsync/package.json
packages/aws-appsync/src/helpers/offline.ts

fix(typescript): Add types info

---

README.md

removed old video

---

packages/aws-appsync-react/package.json
packages/aws-appsync-react/src/offline-helpers.tsx
packages/aws-appsync-react/tsconfig.json
packages/aws-appsync/package.json
packages/aws-appsync/src/helpers/offline.ts
packages/aws-appsync/src/link/auth-link.ts
packages/aws-appsync/src/link/complex-object-link.ts
packages/aws-appsync/src/link/non-terminating-http-link.ts
packages/aws-appsync/src/link/offline-link.ts
packages/aws-appsync/src/types.ts
tutorials/react-offline-realtime-todos/README.md
yarn.lock

fix(typescript): Typescript improvements

---

OFFLINE_HELPERS.md
README.md

chore(docs): Help for offline helpers

---

packages/aws-appsync/__tests__/link/complex-object-link.test.ts
packages/aws-appsync/package.json
packages/aws-appsync/src/link/complex-object-link-uploader.ts
packages/aws-appsync/src/link/complex-object-link.ts
packages/aws-appsync/tsconfig.json
yarn.lock

Fixes #161 
Fixes: #183 
Closes #179 
Closes #204 

test(complex-objects): Add tests for complex objects upload

---

packages/aws-appsync/src/link/auth-link.ts

fix(typescript): Fix types for apiKey and jwtToken

---

packages/aws-appsync/__tests__/link/offline-link.test.ts
packages/aws-appsync/package.json
packages/aws-appsync/src/link/offline-link.ts
tutorials/react-offline-realtime-todos/package.json

Closes #229 
- Fix handling of objects when getting ids for local/remote ids mapping
- Add unit tests
- Run jest with node as testEnvironment

fix(offline): Fix handling of objects when getting ids for local mapping

---

README.md

docs(offline): Error handling and storage engine

---

packages/aws-appsync/src/link/subscription-handshake-link.ts

See:
https://github.com/aws-amplify/amplify-js/pull/1955

fix(subscriptions): Fix NPE when unsubscribing

---

packages/aws-appsync/package.json
packages/aws-appsync/src/cache/offline-cache.ts
packages/aws-appsync/src/client.ts
packages/aws-appsync/src/deltaSync.ts
packages/aws-appsync/src/helpers/offline.ts
packages/aws-appsync/src/link/offline-link.ts
packages/aws-appsync/src/link/retry-link.ts
packages/aws-appsync/src/link/subscription-handshake-link.ts
packages/aws-appsync/src/store.ts
packages/aws-appsync/src/utils/index.ts
yarn.lock

feat(delta-sync): Add DeltaSync support

---

packages/aws-appsync/src/client.ts

fix(delta-sync): Wait for client hydration

---

packages/aws-appsync/src/deltaSync.ts

fix(delta-sync): Change baseQuery fetch policy

---

README.md

updating Vue Apollo Git Repo Link

---

packages/aws-appsync/src/client.ts
packages/aws-appsync/src/link/offline-link.ts

fix(offline): Do not write mutations to cache if fetchPolicy = no-cache

---

packages/aws-appsync/src/cache/offline-cache.ts
packages/aws-appsync/src/client.ts

feat(offline-cache): Add option to prevent storing the ROOT_MUTATION

---

packages/aws-appsync/package.json
packages/aws-appsync/src/cache/offline-cache.ts
packages/aws-appsync/src/deltaSync.ts
packages/aws-appsync/src/helpers/offline.ts
packages/aws-appsync/src/link/offline-link.ts
packages/aws-appsync/src/link/subscription-handshake-link.ts
packages/aws-appsync/src/store.ts
packages/aws-appsync/src/utils/index.ts
packages/aws-appsync/src/utils/logger.ts
yarn.lock

feat(logging): Add logging

---

packages/aws-appsync/src/helpers/offline.ts

#212 
Offline helpers types and fix issue with different options

fix(helpers): Offline helpers types and fix

---

packages/aws-appsync/src/deltaSync.ts

fix(deltasync): Fix error when baseQuery is not specified

---

packages/aws-appsync/src/deltaSync.ts

#366
Store baseQuery correctly including variables.

fix(deltaSync)

---

tutorials/react-offline-realtime-todos/README.md

This PR fixes the followings:
* syncronization -> synchronization
* similated -> simulated
* lifecyle -> lifecycle
* validaton -> validation
* overwite -> overwrite

docs(react-offline-realtime-todos): fix typos in README.md

---

packages/aws-appsync/src/cache/offline-cache.ts
packages/aws-appsync/src/deltaSync.ts

fix(deltaSync): Read last sync timestamps from store if not present in options

---

LICENSE
README.md
packages/aws-appsync-react/LICENSE
packages/aws-appsync-react/package.json
packages/aws-appsync-react/src/index.ts
packages/aws-appsync-react/src/rehydrated-rn.tsx
packages/aws-appsync-react/src/rehydrated.tsx
packages/aws-appsync/LICENSE
packages/aws-appsync/package.json
packages/aws-appsync/src/cache/index.ts
packages/aws-appsync/src/cache/offline-cache.ts
packages/aws-appsync/src/client.ts
packages/aws-appsync/src/deltaSync.ts
packages/aws-appsync/src/helpers/offline.ts
packages/aws-appsync/src/index.ts
packages/aws-appsync/src/link/auth-link.ts
packages/aws-appsync/src/link/complex-object-link-uploader.native.ts
packages/aws-appsync/src/link/complex-object-link-uploader.ts
packages/aws-appsync/src/link/complex-object-link.ts
packages/aws-appsync/src/link/conflict-resolution-link.ts
packages/aws-appsync/src/link/index.ts
packages/aws-appsync/src/link/non-terminating-http-link.ts
packages/aws-appsync/src/link/non-terminating-link.ts
packages/aws-appsync/src/link/offline-link.ts
packages/aws-appsync/src/link/retry-link.ts
packages/aws-appsync/src/link/signer/index.ts
packages/aws-appsync/src/link/subscription-handshake-link.ts
packages/aws-appsync/src/store.ts
packages/aws-appsync/src/types.ts
packages/aws-appsync/src/utils/index.ts

Relicensing to Apache 2.0

---

packages/aws-appsync/src/link/offline-link.ts

Fixes: aws-amplify/amplify-js#3243

fix(offline): Call observer.error when discarding mutation

---

packages/aws-appsync/package.json

syncing aws-sdk versions with aws-amplify 
https://github.com/aws-amplify/amplify-js/pull/3427

Update aws-sdk to latest

---

packages/aws-appsync-react/package.json
packages/aws-appsync-react/src/rehydrated-rn.tsx
packages/aws-appsync-react/src/rehydrated.tsx
packages/aws-appsync/package.json
yarn.lock

Adding support for React Native 0.60 by upgrading redux-offline and using  @react-native-community/netinfo

Native support

---

packages/aws-appsync-react/CHANGELOG.md
packages/aws-appsync/CHANGELOG.md

Add CHANGELOG entries for 2.0.0 release
Addresses issue #463

Add CHANGELOG entries for 2.0.0 release

---

README.md

https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/448#issuecomment-541500109
README update based on issue comment

Updating links usage

---

packages/aws-appsync/__tests__/client.ts

n/a
Adds fetch global and accounts for new package in unit tests

fix(aws-appsync)

---

packages/aws-appsync-auth-link/src/auth-link.ts
packages/aws-appsync-auth-link/src/index.ts
packages/aws-appsync-subscription-link/__tests__/link/realtime-subscription-handshake-link-test.ts
packages/aws-appsync-subscription-link/jest.config.js
packages/aws-appsync-subscription-link/package.json
packages/aws-appsync-subscription-link/src/index.ts
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts
packages/aws-appsync-subscription-link/src/types/index.ts
packages/aws-appsync-subscription-link/src/utils/retry.ts

Adding a new subscription link
usage 
```
const link = ApolloLink.from([
createAuthLink({ url, region, auth }),
createSubscriptionHandshakeLink({ url, region, auth })
]);
```

AWS AppSync new subscription link

---

packages/aws-appsync-auth-link/package.json
packages/aws-appsync-react/package.json
packages/aws-appsync-subscription-link/package.json
packages/aws-appsync/package.json

- aws-appsync-auth-link@2.0.0
- aws-appsync-react@3.0.0
- aws-appsync-subscription-link@2.0.0
- aws-appsync@3.0.0

chore: (aws-mobile-appsync-sdk@3.0)

---

packages/aws-appsync-react/package.json
packages/aws-appsync/src/client.ts

Update AppSync to use latest subscription link

Adding latest subscription link to appsync-client

---

README.md

Since the release of v3, we needed to update the documentation to reflect the new selection set needed.

chore: (Update AppSync Documentation)

---

.gitignore
package.json
packages/aws-appsync-auth-link/package.json
packages/aws-appsync-react/package.json
packages/aws-appsync-subscription-link/package.json
packages/aws-appsync/package.json
packages/aws-appsync/src/client.ts
packages/aws-appsync/src/deltaSync.ts

N/A
- Hoist common devDependencies
- Remove redundant generic types
- Ignore yarn.lock

chore: Fix build

---

package.json
packages/aws-appsync-auth-link/package.json
packages/aws-appsync-react/package.json
packages/aws-appsync/__tests__/client.ts

N/A
- Add jest as devDependency
- Fix test compilation
- Add test script to react package (with `--passWithNoTests`)

chore: Add jest devDependency. Fix test compilation error

---

package.json
packages/aws-appsync/src/link/offline-link.ts

fix(aws-appsync): build issues with ts 3.6 and move to 3.7

---

packages/aws-appsync-auth-link/package.json
packages/aws-appsync-subscription-link/package.json
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts
packages/aws-appsync-subscription-link/src/types/index.ts

#598 #596 #594 #574 #544 #541 #509 #501 #491
Upgrading subscription link to use same logic as AWSAppSyncRealTimeProvider from Amplify JS

Updating subscription link to work same as Amplify

---

packages/aws-appsync-react/package.json
packages/aws-appsync/package.json
packages/aws-appsync/src/client.ts

Reverts awslabs/aws-mobile-appsync-sdk-js#646

Revert "fix: aws-appsync dependencies"

---

README.md
package.json
packages/aws-appsync-auth-link/package.json
packages/aws-appsync-react/package.json
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts
packages/aws-appsync-subscription-link/src/types/index.ts
packages/aws-appsync/package.json
packages/aws-appsync/src/link/offline-link.ts

#647 
Back-port bug fixes from master to be included in the apollo 2 compatible release.
Changes will be published to a non `@latest` npm dist-tag, most likely: `@apollo2`

chore: Preparing apollo2 branch

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts
packages/aws-appsync/src/deltaSync.ts

Currently, the prepare script fails because of a type error. This PR resolves this issue.

fix: add type fixes to fix 'prepare' scripts

---

packages/aws-appsync-subscription-link/__tests__/link/realtime-subscription-handshake-link-test.ts
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

feat: add CD support for Apollo V2

---

.github/CODEOWNERS

chore: Add CODEOWNERS [skip ci]

---

packages/aws-appsync-subscription-link/__tests__/link/realtime-subscription-handshake-link-test.ts
packages/aws-appsync-subscription-link/src/index.ts
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts
packages/aws-appsync-subscription-link/src/types/index.ts

feat: Add keepAliveTimeoutMs config for AppSync WebSocket link (apollov2)

---

packages/aws-appsync-subscription-link/package.json
packages/aws-appsync-subscription-link/src/subscription-handshake-link.ts
packages/aws-appsync-subscription-link/src/types/index.ts

fix(data): port over Angular fix from master

---

README.md

Adding maintenance mode information

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

Fix exception due to illegal access to item in an empty map

---

package.json

pin babel__traverse via resolutions
