packages/aws-appsync/package-lock.json
packages/aws-appsync/package.json
packages/aws-appsync/src/client.js
packages/aws-appsync/src/store.js

Adds the `disableOffline` option to the client to disable offline support
```javascript
const client = new AWSAppSyncClient({
disableOffline: true,
url: appSyncConfig.graphqlEndpoint,
region: appSyncConfig.region,
auth: {
type: appSyncConfig.authenticationType,
apiKey: appSyncConfig.apiKey,
}
});
```

Make offline support optional

---

packages/aws-appsync/README.md
packages/aws-appsync/src/link/subscription-handshake-link.js

when a new request is executed, we need to make sure the observer intially associated with a topic is preserved. currently, on a new request, we disconnect all the clients and then reconnect them and associate them with the **latest** observer. When a subscription message is received, we then fetchthe observer with:
`this.topicObserver.get(topic);`
and call
`observer.next(parsedMessage);`
which will trigger a specific handler configured for that observer (the handler that subscribed to the observer returned by the `execute` function in `QueryManager.startGraphQLSubscription`.
The change keeps track of the previous value of `topicObserver` and retains the observer associated with an existing topic.

Preserve the observer associated with an existing topic

---

packages/aws-appsync/CHANGELOG.md
packages/aws-appsync/src/link/auth-link.js
packages/aws-appsync/src/platform.js
packages/aws-appsync/src/platform.native.js

```
:method	POST
:scheme	https
:path	/graphql
:authority	xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com
accept	*/*
content-type	application/json
user-agent	Expo/2.3.0.1012011 CFNetwork/893.14 Darwin/16.7.0
x-api-key	da1-XXXXXXXXXX-XXXXXXXXXXX
x-amz-user-agent	aws-amplify/1.0.9 react-native
accept-language	en-us
content-length	164
accept-encoding	br, gzip, deflate
```
```
:authority:xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com
:method:POST
:path:/graphql
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.9
content-length:164
content-type:application/json
origin:http://localhost:3000
referer:http://localhost:3000/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) …
```

Update x-amz-user-agent header

---

packages/aws-appsync/CHANGELOG.md
packages/aws-appsync/src/link/subscription-handshake-link.js

Multiple topics can be associated with a client. This happens when
multiple subscriptions are live on a single API. In that case,
clientTopics holds client => [topics]. When the cleanup function is
called, we should look for a topic within an existing list of topics
associated with the client to identify it. Doing this allows us to find
the correct <topic, client> pair which allows us to unsubsribe the
client from the topic and remove the observer tied to the topic. Leaving
a "completed" observer in `topicObserver` will lead to it being reused
if we cancel a subscription and then switch back to it. However since
the observer has been "completed", its `next` function would never be
called.
In `unsubscribeFromTopic` function, we should not delete a `client` key if the
list of subscribed …

Delete observer associated with a topic when cleanup function is called

---

packages/aws-appsync/CHANGELOG.md
packages/aws-appsync/src/link/complex-object-link.js

If val is null (and it could be for a mutation where you want to specifically set a field to null) this crashes as the type of null is "object" (sigh)

Update complex-object-link.js to handle 'null' values

---

packages/aws-appsync/src/link/auth-link.js

Fixes #119
When adding authentication headers via the call to `operation.setContext` in `auth-link.js`, any original headers are overwritten.  This change preserves any original headers that were present on the context.

Preserve original headers (Fixes #119)

---

packages/aws-appsync/src/link/subscription-handshake-link.js

Automatically detect if we should use ssl by inspecting the mqtt url.
---
Why is this useful? We're building an emulator for appsync and one of the roadblocks we ran into is the required use of SSL for the mqtt websocket connections. This is obviously great and what we should use in production but for local development (on the emulator) it would be much easier if we can just pass a normal http (ws://) url and have things "just work".
I tested this via our appsync application (both against our emulator and production AWS)

Detect if we should use ssl via the mqtt url

---

packages/aws-appsync/src/client.ts

N/A
The client instantiation example from the docs will throw a TypeScript error stating that a second parameter is necessary. I've made that second options parameter optional.

Options parameter in AppSyncClient constructor made optional

---

README.md

Fix typo in README pointing to wrong key from AppSync file provided by aws for auth type

update authType to authenticationType as is provided by AppSync.js

---

packages/aws-appsync/src/client.ts

client.mutate - remove JSDoc in favor of TypeScript

fix(typescript): client.mutate - remove JSDoc in favor of TypeScript

---

packages/aws-appsync/src/helpers/offline.ts

To avoid keying on null object
#210 
- implement `isObject` function
- Replace in `getValueByPath` and `findArrayInObject`

Implement `isObject` function: check for `null` and `object` type

---

packages/aws-appsync-react/src/rehydrated-rn.tsx
packages/aws-appsync-react/src/rehydrated.tsx

*Issue #205*
Changes the type of `Rehydrated`'s children from `React.ReactChildren` to `React.ReactNode`.

Fixed Rehydrated children type

---

packages/aws-appsync/src/link/complex-object-link.ts

`Object.keys(false)` was silently failing in android.
Fixes #219 

fix(react-native): Discrepancy in JavaScriptCore iOS vs Android

---

packages/aws-appsync/src/client.ts
packages/aws-appsync/src/link/index.ts
packages/aws-appsync/src/link/non-terminating-http-link.ts
packages/aws-appsync/src/link/non-terminating-link.ts

For starters, thank you so much for this library! It's helping us tremendously 😄 
My situation is:
I am using a lambda resolver on my subscription fields, in order to ensure users only subscribe to events they are authorised to.
My lambda resolver is using it's own auth middleware which reads a token passed in the authorisation header.
Setting this header has to be done on the clients, to do this I am using this code, where it grabs it from my store:
```js
new AWSAppSyncClient(AppSyncConfig, {
link: createAppSyncLink({
...AppSyncConfig,
resultsFetcherLink: ApolloLink.from([
setContext((request, previousContext) => {
const { accessToken } = store.getState()
if (accessToken) {
return ({
headers: {
...previousContext.headers, …
```

Use HttpLink from initial config for subscriptions

---

packages/aws-appsync-react/package.json
packages/aws-appsync/package.json
packages/aws-appsync/src/client.ts
yarn.lock

Fixes #220 
Closes #221 
- Upgrade typescript
- Make all fields in ApolloClientOptions optional

fix(typescript): Make all fields in ApolloClientOptions optional

---

packages/aws-appsync/src/client.ts

Fixes: #218 
Make client.mutate use the same types as Apollo's

fix(typescript): Make client.mutate use the same types as Apollo's

---

packages/aws-appsync/package.json

fixing aws-sdk version to be the same as aws-amplify/core

fix: fixing aws-sdk version to 2.329.0

---

packages/aws-appsync-react/package.json
packages/aws-appsync/__tests__/client.ts
packages/aws-appsync/package.json
packages/aws-appsync/src/link/offline-link.ts
yarn.lock

feat(apollo): Bump apollo client version
chore(dependencies): Make aws-appsync a peerDependency in aws-appsync-react

feat(offline): Provide global callback for error handling

---

packages/aws-appsync/src/helpers/offline.ts

- The updater function in [offline.ts](https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync/src/helpers/offline.ts#L155) on **update/modify of an item filters it from the list and then appends the updated/modified item to the last**. 
- When displaying the list of items, this causes the following unexpected behaviours
- The item jumps from its original position to the last of the list.
- When the entire list is refetched/ when the page reloads the item comes back to its original position
- This PR fixes it by preserving the order in the updater function, by doing a map and replacing the updated/modified item in its original position.
By submitting this pull request, I confirm that you can use, modify, …

preserve order of elements in update cache operation type

---

packages/aws-appsync/src/link/subscription-handshake-link.ts

During the subscription handshake there is an edge case where the server may return a valid GraphQL response:
```
{
extensions: { ... }
data: null,
errors: null,
}
```
Returning  `errors: null` causing an `Uncaught TypeError: Cannot read property 'length' of null` exception within the SDK.
This change is a QoL change for developers who are building tools around AppSync-SDK such as [appsync-emulator-serverless](https://github.com/ConduitVC/aws-utils/tree/master/packages/appsync-emulator-serverless) who may expect AppSync-SDK to handle this type of response

Guard against errors: null response in subscription handshake

---

packages/aws-appsync/src/link/retry-link.ts
packages/aws-appsync/src/link/subscription-handshake-link.ts

- If auto-reconnect when coming back online is needed, users should use  `client.sync` (deltaSync) instead.

fix(subscriptions): Do not retry mqtt disconnections

---

packages/aws-appsync/src/link/auth-link.ts

This fixes an InvalidSignatureExceptions that occurs when using iamBasedAuthentication and the '@@controlEvents' variable in subscriptions.

Remove temporary variables (starting with '@@') before signing

---

tutorials/react-offline-realtime-todos/README.md

I can't find anywhere in the console that I can download a file named AppSync.js... but I have aws-exports.js.
The docs are still very confusing when new to all of these libraries that can be mixed and matched.
I can get the Amplify CLI to work out of the box, but as soon as you try to add AWSAppSyncClient instead and use the Apollo client for offline functionality things get very confusing to me.
*Issue #, if available:* None. Couldn't find any related issues.
I just changed the wording from `AppSync.js` to `aws-exports.js` because that is the only file from `AWS AppSync Console` that I can download, unless I'm missing a step because I didn't create it via the console. I used the `Amplify CLI` to create the resources.
By submitting this pull request, I confirm …

switch AppSync.js to aws-exports.js

---

packages/aws-appsync/__tests__/client.ts
packages/aws-appsync/package.json
packages/aws-appsync/src/client.ts
packages/aws-appsync/src/deltaSync.ts
packages/aws-appsync/src/helpers/offline.ts
packages/aws-appsync/src/link/auth-link.ts
packages/aws-appsync/src/link/offline-link.ts
packages/aws-appsync/src/link/subscription-handshake-link.ts
packages/aws-appsync/src/store.ts
packages/aws-appsync/tsconfig.json
yarn.lock

This PR adds support for having multiple instances of the `AWSAppSyncClient` with `offlineSupport` enabled.
If using more than one client instance, a `keyPrefix` is mandatory for offline support and items in the persisted store will have that prefix.
Also, this PR adds:
- Upgrade Jest
- Increase test coverage
- Improve TypeScript definitions

feat: Multi-client support

---

tutorials/react-offline-realtime-todos/README.md

It seems like the keys `aws-exports.js` have changed since writing the tutorial.

Update keys from aws-exports.js

---

packages/aws-appsync/src/helpers/offline.ts

This change should resolve #421 
Passing an undefined variable to the `path` parameter of [getValueByPath](https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/aws-appsync%401.8.1/packages/aws-appsync/src/helpers/offline.ts#L215) results in an error. This change fixes that issue by setting the default value of `path` to be an empty array.

Fix: TypeError: Cannot read property 'reduce' of undefined

---

packages/aws-appsync-react/package.json
packages/aws-appsync-react/src/rehydrated-rn.tsx
packages/aws-appsync-react/src/rehydrated.tsx
packages/aws-appsync/package.json
yarn.lock

Adding support for React Native 0.60 by upgrading redux-offline and using @react-native-community/netinfo

Add support for React Native 0.60

---

packages/aws-appsync/package.json

Fixes: #439 
Update aws-sdk version to the same as aws-amplify

Update aws-sdk to be the same as amplify

---

README.md

Adding instructions for using the library with React Native >= 0.60 after the 2.00 release
*Related Issues*
#443 
#434 

Adding setup instructions for React Native 0.60

---

packages/aws-appsync/package.json
yarn.lock

#334 
Updates apollo-cache-inmemory from 1.3.10 to 1.3.12.  v.1.3.12 is the minimum increment needed to solve the issue.  Several subsequent minor versions exist, but to be conservative we are taking the minimum needed at this time.  

apollo-cache-inmemory version bump

---

README.md

Update README.md instructions to use NetInfo 4.7.0 for React Native since 5.x.x has breaking changes.

Update README.md instructions to use NetInfo 4.7.0 for React Native

---

tutorials/react-offline-realtime-todos/yarn.lock

We need to update the `yarn.lock` file the React Offline realtime todos in order to resolve the security patches we need for this.
Follow up issue: #540 

chore:(react-offline-realtime-todos) Updating yarn.lock in order to resolve security patches

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

fix for 496
Include the context's header values when establishing a subscription.  This is so subscription data resolvers can access them (as they can with the legacy /mttq implementation)

allow custom headers to be processed by a Subscription resolver's vtl

---

packages/aws-appsync-subscription-link/src/utils/retry.ts

e import '.' to explicitly defining 'index' in retry.ts
I've just setup an Expo/React-Native application and I wanted to use `aws-appsync-subscription-link` and I run into a bug which is related to an import statement. It did only materialize on real iOS/Android devices (haven't tried it on simulators) but it did NOT materialize on RN's web render. To help you reproduce, I quickly paste my `package.json`-s relevant part. I do not know the exact reason though but I managed to make everything work.
```
"dependencies": {
"@apollo/react-hooks": "^3.1.5",
"@eva-design/eva": "^2.0.0",
"@expo/webpack-config": "^0.12.9",
"@react-native-community/masked-view": "^0.1.6",
"@react-native-community/netinfo": "^4.7.0",
"@react-navigation/bottom-tabs": "^5.4.5", …
```

fix(aws-appsync-subscription-link): change relativ

---

README.md
packages/aws-appsync-react/package.json
packages/aws-appsync-react/src/rehydrated-rn.tsx
packages/aws-appsync/package.json

Upgrading redux-offline and netinfo dependencies for react native to use latest versions. This is because newer versions of NetInfo deprecated some APIs that were used by the version of redux-offline we were using.

Upgrading redux-offline and netinfo dependencies for react native

---

packages/aws-appsync-auth-link/package.json
packages/aws-appsync-auth-link/src/auth-link.ts
packages/aws-appsync-subscription-link/__tests__/link/realtime-subscription-handshake-link-test.ts
packages/aws-appsync-subscription-link/package.json
packages/aws-appsync-subscription-link/src/index.ts
packages/aws-appsync-subscription-link/src/non-terminating-http-link.ts
packages/aws-appsync-subscription-link/src/non-terminating-link.ts
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts
packages/aws-appsync-subscription-link/src/subscription-handshake-link.ts

*Issue #:* #525 
*Description of changes:* Updated imports to use the new scoped `@apollo/client` imports. Also bumped version number of both packages to 3.0.0 due to this most likely being a breaking change for consumers (although all tests pass on my machine!)

Updated link packages to use Apollo 3

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

#515 #544 #596 
An if statement to make sure that the `observer` exists before it tries to call the properties of `observer` in timeoutStartSubscriptionAck function

Fix: Avoid error from null value for observer in timeoutStartSubscriptionAck function

---

packages/aws-appsync-auth-link/package.json
packages/aws-appsync/package.json

https://snyk.io/vuln/SNYK-JS-AWSSDK-1059424
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28472

fix: Bump aws-sdk to address CVE-2020-28472

---

packages/aws-appsync-react/package.json
packages/aws-appsync/package.json
packages/aws-appsync/src/client.ts

N/A
Fix dependencies in `aws-appsync` to point to the correct versions.
I had to do some ugly castings as we need the sdk to work with both apollo 2.x and 3.x
Tested with a brand new CRA

fix: aws-appsync dependencies

---

packages/aws-appsync/src/cache/offline-cache.ts
packages/aws-appsync/src/client.ts

*Description of changes:* Removes `storeCacheRootMutation` for security reasons outlined [here](https://github.com/apollographql/apollo-client/issues/3592). The library is secure as this flag defaults to false and call `this.data.delete('ROOT_MUTATION')` here https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/fc173bfe3ce262b1dba422021fc57097c4926b7b/packages/aws-appsync/src/cache/offline-cache.ts#L95-L97 
While this flag defaults to false, we're removing this flag in case user changes this flag and spawn vulnerabilities.

feat(aws-appsync): Remove storeCacheRootMutation flag

---

packages/aws-appsync-auth-link/__tests__/link/auth-link-test.ts
packages/aws-appsync-auth-link/jest.config.js
packages/aws-appsync-auth-link/src/auth-link.ts
packages/aws-appsync-subscription-link/__tests__/link/realtime-subscription-handshake-link-test.ts
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

- Adding lambda authorizer for apollo v2 links (auth and subscription links)
- Small refactor on realtime-handshake
Cypress integration test sample code
```javascript
import { AUTH_TYPE, createAuthLink } from 'aws-appsync-auth-link';
import { createSubscriptionHandshakeLink } from 'aws-appsync-subscription-link';
import { ApolloLink } from 'apollo-link';
import { createHttpLink } from 'apollo-link-http';
import ApolloClient from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import gql from 'graphql-tag'
const url = 'https://xxxxxxxxx.appsync-api.us-west-2.amazonaws.com/graphql';
const region = …
```

Feat: lambda authorizer apollov2

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

Currently, the `prepare` script fails because of a type error. This PR resolves this issue.

fix: add type fix to subscription link to fix 'prepare' script

---

packages/aws-appsync/package.json

https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/632
Removes RN-specific peer dependencies from aws-appsync package.json. 
Peer dependencies are supposed to be used to let consumers of a package know which host/top-level dependencies and versions thereof they need to have installed in their app in order for this package to work as expected. But those dependencies should always be needed. Peer deps should not be used for conditional dependencies that are needed in some cases but not in most, like what we’re doing here.
On NPM 6 and below, having the RN-related deps listed under peer dependencies would always throw a warning during `npm install` if customers don't have those `@react-native-community/*` dependencies installed even …

chore(aws-appsync): remove rn peerDeps

---

README.md
packages/aws-appsync/package.json

#654
#642 
Upgrade from `@react-native-community/async-storage` to `@react-native-async-storage/async-storage`
Also upgrading `@redux-offline/redux-offline` to `2.6.0-native.1` as the old version depends on `@react-native-community/async-storage`

Upgrade to @react-native-async-storage/async-storage

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

fix: Port over Amplify fix for subscription race conditions for ApolloV2
#509 
There was a fix in [Amplify JS](https://github.com/aws-amplify/amplify-js/pull/4956) to handle subscription race conditions (for instance, on mount / unmount). Porting these over to the AppSync SDK

fix: Port over Amplify fix for subscription race conditions for ApolloV2

---

README.md

Updating README for Using Authorization and Subscription links with Apollo Client V3
n/a
updated the readme to use ApolloProvider, ApolloClient, InMemoryCache, HttpLink, and ApolloLink from @apollo/client

Updating README for Using Authorization and Subscription links with Apollo Client V3

---

packages/aws-appsync/package.json

*Issue #699*
This PR fixes the syntax of the graphql peer dependencies in aws-appsync package (apollov2)
the syntax can for example be checked on https://semver.npmjs.com/

fix: peer dependency syntax #699

---

packages/aws-appsync-subscription-link/__tests__/link/realtime-subscription-handshake-link-test.ts
packages/aws-appsync-subscription-link/src/index.ts
packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts
packages/aws-appsync-subscription-link/src/types/index.ts

N/A
Adds an optional flag (`keepAliveTimeoutMs`) for the AppSync WebSocket Apollo link

feat: Add keepAliveTimeoutMs config for AppSync WebSocket link

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/688
Code does not check whether observer is null or undefined which sometimes happen.
I added a check similar to the checks being done earlier in the same function.

added check for observer being null

---

packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts

Backport https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/735

fix: added check for observer to apollov2

---

packages/aws-appsync/package.json

Installing graphql 15.4.0 or higher results in an install error and a runtime error.
Install error:
```
$ npm install graphql@15.8.0
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: apollo-cache-inmemory@1.3.12
npm WARN Found: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   graphql@"15.8.0" from the root project
npm WARN   6 more (apollo-cache, apollo-link, apollo-link-http-common, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"0.11.7 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-cache-inmemory@1.3.12
npm WARN node_modules/aws-appsync/node_modules/apollo-cache-inmemory
npm WARN   apollo-cache-inmemory@"1.3.12" from aws-appsync@4.1.7
npm WARN   node_modules/aws-appsync
npm WARN 
npm WARN Conflicting peer …
```

chore: set max graphql version
